title: Shirley Zhang
logo: /assets/img/logo.jpg
description: Shirley's personal website
show_downloads: false
google_analytics: UA-195366952-1
theme: jekyll-theme-minimal

author: Shirley Zhang
email: theshirleyzhang@gmail.com


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/eugenie-lai
  GitHub: https://github.com/eugenielai
